CREATE TABLE MATCH_RECORD(
	PLAY_NO VARCHAR2(100) NOT NULL,
	R_PLAY_STATE NUMBER(3) NOT NULL,
	ED_PLAY_STATE NUMBER(3) NOT NULL,
	PLAY_DATE DATE,
	PLAY_PLACE VARCHAR2(100),
	JUDGE VARCHAR2(14),
	REQUEST_TEAM_NO NUMBER(5) NOT NULL, 
	R_TEAM_DIRECTOR VARCHAR2(30), 
	R_TEAM_SCORER VARCHAR2(30), 
	ED_TEAM_NO NUMBER(5) NOT NULL, 
	ED_TEAM_DIRECTOR VARCHAR2(30), 
	ED_TEAM_SCORER VARCHAR2(30)
);