team_no는 추후 시퀀스로

CREATE TABLE TEAM(
TEAM_NO NUMBER(4) PRIMARY KEY,
TEAM_NAME VARCHAR2(30),
DIRECTOR_ID VARCHAR2(30),
FOUND_DATE VARCHAR2(10),
TEL VARCHAR2(30),
EMAIL VARCHAR2(50),
PREFER_GROUND VARCHAR2(40),
PREFER_TIME VARCHAR2(30),
MEMBERSHIP_FEE NUMBER(10),
JOIN_CONDITION VARCHAR2(3000),
ORGPROFILEPHOTO VARCHAR2(100),
NEWPROFILEPHOTO VARCHAR2(100),
CONTEXT VARCHAR2(3000),
STATEMENT NUMBER(1),
POINT NUMBER(10),
JOIN_DATE DATE
);

CREATE sequence team_seq;

CREATE table teamsub(
applicant varchar2(20) not null,  
acceptor varchar2(20) not null, 
app_statement number(5), 
acc_statement number(5)
)