CREATE table team_record(
teamno number(4) not null,
playno varchar2(30) not null,
playDate date not null,
playTeam varchar2(30) not null,
opposingTeam varchar2(30) not null,
director varchar2(14) not null,
scorer varchar2(14) not null,
success2p number(5),
try2p number(5),
success3p number(5),
try3p number(5),
success1p number(5),
try1p number(5),
rebound number(5),
assist number(5),
blocking number(5),
steal number(5),
foul number(5),
mannerPoint number(5));